appname: postmail

charset: UTF-8

postmail:
    queue: /queue/postmail
    tls: 0
    email:
        host: smtp.foo.com
        port: 25
        username:
        password:

plugins:
    Stomp:
        postmail:
            hostname: localhost