appname: postmail

charset: UTF-8

postmail:
    stomp:
        queue: /queue/postmail
    email:
        host: smtp.foo.com
        port: 25
        username:
        password:

plugins:
    Stomp:
        postmail:
            hostname: localhost
