appname: postmail

charset: UTF-8

postmail:
    queue: /queue/postmail
    email:
        host: smtp.googlemail.com
        port: 587
        username: khaled@crowdtilt.com
        password: welcomewelcome

plugins:
    Stomp:
        postmail:
            hostname: localhost
            port: 61613
